name: Build Windows Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: 下载 ffmpeg
        run: |
          mkdir ffmpeg
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          tar -xf ffmpeg.zip -C ffmpeg --strip-components=1
          copy ffmpeg\bin\ffmpeg.exe ffmpeg\ffmpeg.exe
          copy ffmpeg\bin\ffprobe.exe ffmpeg\ffprobe.exe

      - name: 打包应用
        run: |
          python build-windows.py

      - name: 打包发布包
        run: |
          cd release
          powershell Compress-Archive -Path * -DestinationPath ..\视频抽帧工具-Windows.zip -Force
          cd ..

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: 视频抽帧工具-Windows
          path: 视频抽帧工具-Windows.zip 